<%@ Page Title="" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="QuanLyViTriKhoMoi.aspx.cs" Inherits="ALSE.QuanLyViTriKhoMoi" %>

<asp:Content ID="Content1" ContentPlaceHolderID="HeadContent" runat="server">
    <%# Versioned.VersionedFiles.ScriptHelper.Render("css","../css/custom/QuanLyViTriKhoMoi.css") %>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="MainContent" runat="server">
    <div id="qlvtkm-right">
        <div class="row">
            <div class="col-sm-1">
                <table class="table table-bordered" id="table-rack-12">
                    <tr>
                        <td data-toggle="tooltip" title="Đây là số 1 của rack 1">1</td>
                    </tr>
                    <tr>
                        <td data-toggle="tooltip" title="Đây là số 2 của rack 1">2</td>
                    </tr>
                    <tr>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>4</td>
                    </tr>
                    <tr>
                        <td>5</td>
                    </tr>
                    <tr>
                        <td>6</td>
                    </tr>
                    <tr>
                        <td>7</td>
                    </tr>
                    <tr>
                        <td>8</td>
                    </tr>
                    <tr>
                        <td>9</td>
                    </tr>
                    <tr>
                        <td>10</td>
                    </tr>
                    <tr>
                        <td>11</td>
                    </tr>
                    <tr>
                        <td>12</td>
                    </tr>
                    <tr>
                        <td>13</td>
                    </tr>
                    <tr>
                        <td>14</td>
                    </tr>
                    <tr>
                        <td>15</td>
                    </tr>
                    <tr>
                        <td>16</td>
                    </tr>
                    <tr>
                        <td>17</td>
                    </tr>
                    <tr>
                        <td>18</td>
                    </tr>
                    <tr>
                        <td>19</td>
                    </tr>
                    <tr>
                        <td>20</td>
                    </tr>
                    <tr>
                        <td>21</td>
                    </tr>
                    <tr>
                        <td>22</td>
                    </tr>
                    <tr>
                        <td>23</td>
                    </tr>
                    <tr>
                        <td>24</td>
                    </tr>
                    <tr>
                        <td>25</td>
                    </tr>
                    <tr>
                        <td>26</td>
                    </tr>
                    <tr>
                        <td>27</td>
                    </tr>
                    <tr>
                        <td>28</td>
                    </tr>
                    <tr>
                        <td>29</td>
                    </tr>
                    <tr>
                        <td>30</td>
                    </tr>
                    <tr>
                        <td>31</td>
                    </tr>
                    <tr>
                        <td>32</td>
                    </tr>
                    <tr>
                        <td>33</td>
                    </tr>
                    <tr>
                        <td>34</td>
                    </tr>
                    <tr>
                        <td>35</td>
                    </tr>
                    <tr>
                        <td>36</td>
                    </tr>
                    <tr>
                        <td>37</td>
                    </tr>
                    <tr>
                        <td>38</td>
                    </tr>
                    <tr>
                        <td>39</td>
                    </tr>
                    <tr>
                        <td>40</td>
                    </tr>
                    <tr>
                        <td>41</td>
                    </tr>
                    <tr>
                        <td>42</td>
                    </tr>

                </table>
            </div>
            <div class="col-sm-2">
                <div class="row">
                    <div class="col-sm-2">
                        <table class="table table-bordered" id="table-rack-11">
                            <tr>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>3</td>
                            </tr>
                            <tr>
                                <td>4</td>
                            </tr>
                            <tr>
                                <td>5</td>
                            </tr>
                            <tr>
                                <td>6</td>
                            </tr>
                            <tr>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>8</td>
                            </tr>
                            <tr>
                                <td>9</td>
                            </tr>
                            <tr>
                                <td>10</td>
                            </tr>
                            <tr>
                                <td>11</td>
                            </tr>
                            <tr>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>13</td>
                            </tr>
                            <tr>
                                <td>14</td>
                            </tr>
                            <tr>
                                <td>15</td>
                            </tr>
                            <tr>
                                <td>16</td>
                            </tr>
                            <tr>
                                <td>17</td>
                            </tr>
                            <tr>
                                <td>18</td>
                            </tr>
                            <tr>
                                <td>19</td>
                            </tr>
                            <tr>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>21</td>
                            </tr>
                            <tr>
                                <td>22</td>
                            </tr>
                            <tr>
                                <td>23</td>
                            </tr>
                            <tr>
                                <td>24</td>
                            </tr>
                            <tr>
                                <td>25</td>
                            </tr>
                            <tr>
                                <td>26</td>
                            </tr>
                            <tr>
                                <td>27</td>
                            </tr>
                            <tr>
                                <td>28</td>
                            </tr>
                            <tr>
                                <td>29</td>
                            </tr>
                            <tr>
                                <td>30</td>
                            </tr>
                            <tr>
                                <td>31</td>
                            </tr>
                            <tr>
                                <td>32</td>
                            </tr>
                            <tr>
                                <td>33</td>
                            </tr>
                            <tr>
                                <td>34</td>
                            </tr>
                            <tr>
                                <td>35</td>
                            </tr>
                            <tr>
                                <td>36</td>
                            </tr>
                            <tr>
                                <td>37</td>
                            </tr>
                            <tr>
                                <td>38</td>
                            </tr>
                            <tr>
                                <td>39</td>
                            </tr>
                            <tr>
                                <td>40</td>
                            </tr>
                            <tr>
                                <td>41</td>
                            </tr>
                            <tr>
                                <td>42</td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-sm-2">
                        <table class="table table-bordered" id="table-rack-10">
                            <tr>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>3</td>
                            </tr>
                            <tr>
                                <td>4</td>
                            </tr>
                            <tr>
                                <td>5</td>
                            </tr>
                            <tr>
                                <td>6</td>
                            </tr>
                            <tr>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>8</td>
                            </tr>
                            <tr>
                                <td>9</td>
                            </tr>
                            <tr>
                                <td>10</td>
                            </tr>
                            <tr>
                                <td>11</td>
                            </tr>
                            <tr>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>13</td>
                            </tr>
                            <tr>
                                <td>14</td>
                            </tr>
                            <tr>
                                <td>15</td>
                            </tr>
                            <tr>
                                <td>16</td>
                            </tr>
                            <tr>
                                <td>17</td>
                            </tr>
                            <tr>
                                <td>18</td>
                            </tr>
                            <tr>
                                <td>19</td>
                            </tr>
                            <tr>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>21</td>
                            </tr>
                            <tr>
                                <td>22</td>
                            </tr>
                            <tr>
                                <td>23</td>
                            </tr>
                            <tr>
                                <td>24</td>
                            </tr>
                            <tr>
                                <td>25</td>
                            </tr>
                            <tr>
                                <td>26</td>
                            </tr>
                            <tr>
                                <td>27</td>
                            </tr>
                            <tr>
                                <td>28</td>
                            </tr>
                            <tr>
                                <td>29</td>
                            </tr>
                            <tr>
                                <td>30</td>
                            </tr>
                            <tr>
                                <td>31</td>
                            </tr>
                            <tr>
                                <td>32</td>
                            </tr>
                            <tr>
                                <td>33</td>
                            </tr>
                            <tr>
                                <td>34</td>
                            </tr>
                            <tr>
                                <td>35</td>
                            </tr>
                            <tr>
                                <td>36</td>
                            </tr>
                            <tr>
                                <td>37</td>
                            </tr>
                            <tr>
                                <td>38</td>
                            </tr>
                            <tr>
                                <td>39</td>
                            </tr>
                            <tr>
                                <td>40</td>
                            </tr>
                            <tr>
                                <td>41</td>
                            </tr>
                            <tr>
                                <td>42</td>
                            </tr>
                        </table>
                    </div>
                </div>


            </div>
            <div class="col-sm-2">
                <div class="row">
                    <div class="col-sm-2">
                        <table class="table table-bordered" id="table-rack-9">
                            <tr>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>3</td>
                            </tr>
                            <tr>
                                <td>4</td>
                            </tr>
                            <tr>
                                <td>5</td>
                            </tr>
                            <tr>
                                <td>6</td>
                            </tr>
                            <tr>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>8</td>
                            </tr>
                            <tr>
                                <td>9</td>
                            </tr>
                            <tr>
                                <td>10</td>
                            </tr>
                            <tr>
                                <td>11</td>
                            </tr>
                            <tr>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>13</td>
                            </tr>
                            <tr>
                                <td>14</td>
                            </tr>
                            <tr>
                                <td>15</td>
                            </tr>
                            <tr>
                                <td>16</td>
                            </tr>
                            <tr>
                                <td>17</td>
                            </tr>
                            <tr>
                                <td>18</td>
                            </tr>
                            <tr>
                                <td>19</td>
                            </tr>
                            <tr>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>21</td>
                            </tr>
                            <tr>
                                <td>22</td>
                            </tr>
                            <tr>
                                <td>23</td>
                            </tr>
                            <tr>
                                <td>24</td>
                            </tr>
                            <tr>
                                <td>25</td>
                            </tr>
                            <tr>
                                <td>26</td>
                            </tr>
                            <tr>
                                <td>27</td>
                            </tr>
                            <tr>
                                <td>28</td>
                            </tr>
                            <tr>
                                <td>29</td>
                            </tr>
                            <tr>
                                <td>30</td>
                            </tr>
                            <tr>
                                <td>31</td>
                            </tr>
                            <tr>
                                <td>32</td>
                            </tr>
                            <tr>
                                <td>33</td>
                            </tr>
                            <tr>
                                <td>34</td>
                            </tr>
                            <tr>
                                <td>35</td>
                            </tr>
                            <tr>
                                <td>36</td>
                            </tr>
                            <tr>
                                <td>37</td>
                            </tr>
                            <tr>
                                <td>38</td>
                            </tr>
                            <tr>
                                <td>39</td>
                            </tr>
                            <tr>
                                <td>40</td>
                            </tr>
                            <tr>
                                <td>41</td>
                            </tr>
                            <tr>
                                <td>42</td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-sm-2">
                        <table class="table table-bordered" id="table-rack-8">
                            <tr>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>3</td>
                            </tr>
                            <tr>
                                <td>4</td>
                            </tr>
                            <tr>
                                <td>5</td>
                            </tr>
                            <tr>
                                <td>6</td>
                            </tr>
                            <tr>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>8</td>
                            </tr>
                            <tr>
                                <td>9</td>
                            </tr>
                            <tr>
                                <td>10</td>
                            </tr>
                            <tr>
                                <td>11</td>
                            </tr>
                            <tr>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>13</td>
                            </tr>
                            <tr>
                                <td>14</td>
                            </tr>
                            <tr>
                                <td>15</td>
                            </tr>
                            <tr>
                                <td>16</td>
                            </tr>
                            <tr>
                                <td>17</td>
                            </tr>
                            <tr>
                                <td>18</td>
                            </tr>
                            <tr>
                                <td>19</td>
                            </tr>
                            <tr>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>21</td>
                            </tr>
                            <tr>
                                <td>22</td>
                            </tr>
                            <tr>
                                <td>23</td>
                            </tr>
                            <tr>
                                <td>24</td>
                            </tr>
                            <tr>
                                <td>25</td>
                            </tr>
                            <tr>
                                <td>26</td>
                            </tr>
                            <tr>
                                <td>27</td>
                            </tr>
                            <tr>
                                <td>28</td>
                            </tr>
                            <tr>
                                <td>29</td>
                            </tr>
                            <tr>
                                <td>30</td>
                            </tr>
                            <tr>
                                <td>31</td>
                            </tr>
                            <tr>
                                <td>32</td>
                            </tr>
                            <tr>
                                <td>33</td>
                            </tr>
                            <tr>
                                <td>34</td>
                            </tr>
                            <tr>
                                <td>35</td>
                            </tr>
                            <tr>
                                <td>36</td>
                            </tr>
                            <tr>
                                <td>37</td>
                            </tr>
                            <tr>
                                <td>38</td>
                            </tr>
                            <tr>
                                <td>39</td>
                            </tr>
                            <tr>
                                <td>40</td>
                            </tr>
                            <tr>
                                <td>41</td>
                            </tr>
                            <tr>
                                <td>42</td>
                            </tr>
                        </table>
                    </div>
                </div>


            </div>
            <div class="col-sm-2">
                <div class="row">
                    <div class="col-sm-2">
                        <table class="table table-bordered" id="table-rack-7">
                            <tr>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>3</td>
                            </tr>
                            <tr>
                                <td>4</td>
                            </tr>
                            <tr>
                                <td>5</td>
                            </tr>
                            <tr>
                                <td>6</td>
                            </tr>
                            <tr>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>8</td>
                            </tr>
                            <tr>
                                <td>9</td>
                            </tr>
                            <tr>
                                <td>10</td>
                            </tr>
                            <tr>
                                <td>11</td>
                            </tr>
                            <tr>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>13</td>
                            </tr>
                            <tr>
                                <td>14</td>
                            </tr>
                            <tr>
                                <td>15</td>
                            </tr>
                            <tr>
                                <td>16</td>
                            </tr>
                            <tr>
                                <td>17</td>
                            </tr>
                            <tr>
                                <td>18</td>
                            </tr>
                            <tr>
                                <td>19</td>
                            </tr>
                            <tr>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>21</td>
                            </tr>
                            <tr>
                                <td>22</td>
                            </tr>
                            <tr>
                                <td>23</td>
                            </tr>
                            <tr>
                                <td>24</td>
                            </tr>
                            <tr>
                                <td>25</td>
                            </tr>
                            <tr>
                                <td>26</td>
                            </tr>
                            <tr>
                                <td>27</td>
                            </tr>
                            <tr>
                                <td>28</td>
                            </tr>
                            <tr>
                                <td>29</td>
                            </tr>
                            <tr>
                                <td>30</td>
                            </tr>
                            <tr>
                                <td>31</td>
                            </tr>
                            <tr>
                                <td>32</td>
                            </tr>
                            <tr>
                                <td>33</td>
                            </tr>
                            <tr>
                                <td>34</td>
                            </tr>
                            <tr>
                                <td>35</td>
                            </tr>
                            <tr>
                                <td>36</td>
                            </tr>
                            <tr>
                                <td>37</td>
                            </tr>
                            <tr>
                                <td>38</td>
                            </tr>
                            <tr>
                                <td>39</td>
                            </tr>
                            <tr>
                                <td>40</td>
                            </tr>
                            <tr>
                                <td>41</td>
                            </tr>
                            <tr>
                                <td>42</td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-sm-2">
                        <table class="table table-bordered" id="table-rack-6">
                            <tr>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>3</td>
                            </tr>
                            <tr>
                                <td>4</td>
                            </tr>
                            <tr>
                                <td>5</td>
                            </tr>
                            <tr>
                                <td>6</td>
                            </tr>
                            <tr>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>8</td>
                            </tr>
                            <tr>
                                <td>9</td>
                            </tr>
                            <tr>
                                <td>10</td>
                            </tr>
                            <tr>
                                <td>11</td>
                            </tr>
                            <tr>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>13</td>
                            </tr>
                            <tr>
                                <td>14</td>
                            </tr>
                            <tr>
                                <td>15</td>
                            </tr>
                            <tr>
                                <td>16</td>
                            </tr>
                            <tr>
                                <td>17</td>
                            </tr>
                            <tr>
                                <td>18</td>
                            </tr>
                            <tr>
                                <td>19</td>
                            </tr>
                            <tr>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>21</td>
                            </tr>
                            <tr>
                                <td>22</td>
                            </tr>
                            <tr>
                                <td>23</td>
                            </tr>
                            <tr>
                                <td>24</td>
                            </tr>
                            <tr>
                                <td>25</td>
                            </tr>
                            <tr>
                                <td>26</td>
                            </tr>
                            <tr>
                                <td>27</td>
                            </tr>
                            <tr>
                                <td>28</td>
                            </tr>
                            <tr>
                                <td>29</td>
                            </tr>
                            <tr>
                                <td>30</td>
                            </tr>
                            <tr>
                                <td>31</td>
                            </tr>
                            <tr>
                                <td>32</td>
                            </tr>
                            <tr>
                                <td>33</td>
                            </tr>
                            <tr>
                                <td>34</td>
                            </tr>
                            <tr>
                                <td>35</td>
                            </tr>
                            <tr>
                                <td>36</td>
                            </tr>
                            <tr>
                                <td>37</td>
                            </tr>
                            <tr>
                                <td>38</td>
                            </tr>
                            <tr>
                                <td>39</td>
                            </tr>
                            <tr>
                                <td>40</td>
                            </tr>
                            <tr>
                                <td>41</td>
                            </tr>
                            <tr>
                                <td>42</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="row">
                    <div class="col-sm-2">
                        <table class="table table-bordered" id="table-rack-5">
                            <tr>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>3</td>
                            </tr>
                            <tr>
                                <td>4</td>
                            </tr>
                            <tr>
                                <td>5</td>
                            </tr>
                            <tr>
                                <td>6</td>
                            </tr>
                            <tr>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>8</td>
                            </tr>
                            <tr>
                                <td>9</td>
                            </tr>
                            <tr>
                                <td>10</td>
                            </tr>
                            <tr>
                                <td>11</td>
                            </tr>
                            <tr>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>13</td>
                            </tr>
                            <tr>
                                <td>14</td>
                            </tr>
                            <tr>
                                <td>15</td>
                            </tr>
                            <tr>
                                <td>16</td>
                            </tr>
                            <tr>
                                <td>17</td>
                            </tr>
                            <tr>
                                <td>18</td>
                            </tr>
                            <tr>
                                <td>19</td>
                            </tr>
                            <tr>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>21</td>
                            </tr>
                            <tr>
                                <td>22</td>
                            </tr>
                            <tr>
                                <td>23</td>
                            </tr>
                            <tr>
                                <td>24</td>
                            </tr>
                            <tr>
                                <td>25</td>
                            </tr>
                            <tr>
                                <td>26</td>
                            </tr>
                            <tr>
                                <td>27</td>
                            </tr>
                            <tr>
                                <td>28</td>
                            </tr>
                            <tr>
                                <td>29</td>
                            </tr>
                            <tr>
                                <td>30</td>
                            </tr>
                            <tr>
                                <td>31</td>
                            </tr>
                            <tr>
                                <td>32</td>
                            </tr>
                            <tr>
                                <td>33</td>
                            </tr>
                            <tr>
                                <td>34</td>
                            </tr>
                            <tr>
                                <td>35</td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-sm-2">
                        <table class="table table-bordered" id="table-rack-4">
                            <tr>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>3</td>
                            </tr>
                            <tr>
                                <td>4</td>
                            </tr>
                            <tr>
                                <td>5</td>
                            </tr>
                            <tr>
                                <td>6</td>
                            </tr>
                            <tr>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>8</td>
                            </tr>
                            <tr>
                                <td>9</td>
                            </tr>
                            <tr>
                                <td>10</td>
                            </tr>
                            <tr>
                                <td>11</td>
                            </tr>
                            <tr>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>13</td>
                            </tr>
                            <tr>
                                <td>14</td>
                            </tr>
                            <tr>
                                <td>15</td>
                            </tr>
                            <tr>
                                <td>16</td>
                            </tr>
                            <tr>
                                <td>17</td>
                            </tr>
                            <tr>
                                <td>18</td>
                            </tr>
                            <tr>
                                <td>19</td>
                            </tr>
                            <tr>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>21</td>
                            </tr>
                            <tr>
                                <td>22</td>
                            </tr>
                            <tr>
                                <td>23</td>
                            </tr>
                            <tr>
                                <td>24</td>
                            </tr>
                            <tr>
                                <td>25</td>
                            </tr>
                            <tr>
                                <td>26</td>
                            </tr>
                            <tr>
                                <td>27</td>
                            </tr>
                            <tr>
                                <td>28</td>
                            </tr>
                            <tr>
                                <td>29</td>
                            </tr>
                            <tr>
                                <td>30</td>
                            </tr>
                            <tr>
                                <td>31</td>
                            </tr>
                            <tr>
                                <td>32</td>
                            </tr>
                            <tr>
                                <td>33</td>
                            </tr>
                            <tr>
                                <td>34</td>
                            </tr>
                            <tr>
                                <td>35</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-sm-2">
                <div class="row">
                    <div class="col-sm-2">
                        <table class="table table-bordered" id="table-rack-3">
                            <tr>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>3</td>
                            </tr>
                            <tr>
                                <td>4</td>
                            </tr>
                            <tr>
                                <td>5</td>
                            </tr>
                            <tr>
                                <td>6</td>
                            </tr>
                            <tr>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>8</td>
                            </tr>
                            <tr>
                                <td>9</td>
                            </tr>
                            <tr>
                                <td>10</td>
                            </tr>
                            <tr>
                                <td>11</td>
                            </tr>
                            <tr>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>13</td>
                            </tr>
                            <tr>
                                <td>14</td>
                            </tr>
                            <tr>
                                <td>15</td>
                            </tr>
                            <tr>
                                <td>16</td>
                            </tr>
                            <tr>
                                <td>17</td>
                            </tr>
                            <tr>
                                <td>18</td>
                            </tr>
                            <tr>
                                <td>19</td>
                            </tr>
                            <tr>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>21</td>
                            </tr>
                            <tr>
                                <td>22</td>
                            </tr>
                            <tr>
                                <td>23</td>
                            </tr>
                            <tr>
                                <td>24</td>
                            </tr>
                            <tr>
                                <td>25</td>
                            </tr>
                            <tr>
                                <td>26</td>
                            </tr>
                            <tr>
                                <td>27</td>
                            </tr>
                            <tr>
                                <td>28</td>
                            </tr>
                            <tr>
                                <td>29</td>
                            </tr>
                            <tr>
                                <td>30</td>
                            </tr>
                            <tr>
                                <td>31</td>
                            </tr>
                            <tr>
                                <td>32</td>
                            </tr>
                            <tr>
                                <td>33</td>
                            </tr>
                            <tr>
                                <td>34</td>
                            </tr>
                            <tr>
                                <td>35</td>
                            </tr>
                        </table>
                    </div>
                    <div class="col-sm-2">
                        <table class="table table-bordered" id="table-rack-2">
                            <tr>
                                <td>1</td>
                            </tr>
                            <tr>
                                <td>2</td>
                            </tr>
                            <tr>
                                <td>3</td>
                            </tr>
                            <tr>
                                <td>4</td>
                            </tr>
                            <tr>
                                <td>5</td>
                            </tr>
                            <tr>
                                <td>6</td>
                            </tr>
                            <tr>
                                <td>7</td>
                            </tr>
                            <tr>
                                <td>8</td>
                            </tr>
                            <tr>
                                <td>9</td>
                            </tr>
                            <tr>
                                <td>10</td>
                            </tr>
                            <tr>
                                <td>11</td>
                            </tr>
                            <tr>
                                <td>12</td>
                            </tr>
                            <tr>
                                <td>13</td>
                            </tr>
                            <tr>
                                <td>14</td>
                            </tr>
                            <tr>
                                <td>15</td>
                            </tr>
                            <tr>
                                <td>16</td>
                            </tr>
                            <tr>
                                <td>17</td>
                            </tr>
                            <tr>
                                <td>18</td>
                            </tr>
                            <tr>
                                <td>19</td>
                            </tr>
                            <tr>
                                <td>20</td>
                            </tr>
                            <tr>
                                <td>21</td>
                            </tr>
                            <tr>
                                <td>22</td>
                            </tr>
                            <tr>
                                <td>23</td>
                            </tr>
                            <tr>
                                <td>24</td>
                            </tr>
                            <tr>
                                <td>25</td>
                            </tr>
                            <tr>
                                <td>26</td>
                            </tr>
                            <tr>
                                <td>27</td>
                            </tr>
                            <tr>
                                <td>28</td>
                            </tr>
                            <tr>
                                <td>29</td>
                            </tr>
                            <tr>
                                <td>30</td>
                            </tr>
                            <tr>
                                <td>31</td>
                            </tr>
                            <tr>
                                <td>32</td>
                            </tr>
                            <tr>
                                <td>33</td>
                            </tr>
                            <tr>
                                <td>34</td>
                            </tr>
                            <tr>
                                <td>35</td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-sm-1">
                <table class="table table-bordered" id="table-rack-1">
                    <tr>
                        <td>1</td>
                    </tr>
                    <tr>
                        <td>2</td>
                    </tr>
                    <tr>
                        <td>3</td>
                    </tr>
                    <tr>
                        <td>4</td>
                    </tr>
                    <tr>
                        <td>5</td>
                    </tr>
                    <tr>
                        <td>6</td>
                    </tr>
                    <tr>
                        <td>7</td>
                    </tr>
                    <tr>
                        <td>8</td>
                    </tr>
                    <tr>
                        <td>9</td>
                    </tr>
                    <tr>
                        <td>10</td>
                    </tr>
                    <tr>
                        <td>11</td>
                    </tr>
                    <tr>
                        <td>12</td>
                    </tr>
                    <tr>
                        <td>13</td>
                    </tr>
                    <tr>
                        <td>14</td>
                    </tr>
                    <tr>
                        <td>15</td>
                    </tr>
                    <tr>
                        <td>16</td>
                    </tr>
                    <tr>
                        <td>17</td>
                    </tr>
                    <tr>
                        <td>18</td>
                    </tr>
                    <tr>
                        <td>19</td>
                    </tr>
                    <tr>
                        <td>20</td>
                    </tr>
                    <tr>
                        <td>21</td>
                    </tr>
                    <tr>
                        <td>22</td>
                    </tr>
                    <tr>
                        <td>23</td>
                    </tr>
                    <tr>
                        <td>24</td>
                    </tr>
                    <tr>
                        <td>25</td>
                    </tr>
                    <tr>
                        <td>26</td>
                    </tr>
                    <tr>
                        <td>27</td>
                    </tr>
                    <tr>
                        <td>28</td>
                    </tr>
                    <tr>
                        <td>29</td>
                    </tr>
                    <tr>
                        <td>30</td>
                    </tr>
                    <tr>
                        <td>31</td>
                    </tr>
                    <tr>
                        <td>32</td>
                    </tr>
                    <tr>
                        <td>33</td>
                    </tr>
                    <tr>
                        <td>34</td>
                    </tr>
                    <tr>
                        <td>35</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div id="qlvtkm-left">
        <div class="row">
            <div class="col-sm-6">
                123
            </div>
            <div class="col-sm-6">
                456
            </div>
        </div>
    </div>

    <%# Versioned.VersionedFiles.ScriptHelper.Render("js","../js/custom/QuanLyViTriKhoMoi.js") %>
</asp:Content>
